name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
version: ${project.version}
description: ${project.artifactId} Bukkit Plugin
author: BillyGalbreath

commands:
    pl3xsigns:
        description: Reload config
        usage: /<command> (reload)
        aliases:
        - pl3xsign
        - signs
        - sign
        - ps

permissions:
    command.pl3xsigns:
        description: Reload config
        default: op
